# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InjDK-zKwb0WT9vHAIScp05oI0em9Yyd
"""

import streamlit as st
import pandas as pd
from transformers import pipeline

# 1. Page Configuration
st.set_page_config(page_title="Dhurandhar 2 Sentiment Analyzer", page_icon="🎬", layout="centered")

# 2. Load the LLM Model (Cached for performance)
@st.cache_resource
def load_sentiment_model():
    # Using the exact model from your Colab notebook
    return pipeline('sentiment-analysis', model='distilbert-base-uncased-finetuned-sst-2-english')

st.title("🎬 Dhurandhar 2: Movie Review Sentiment Analyzer")
st.write("This application uses a Hugging Face Transformer model (`distilbert-base-uncased`) to analyze the sentiment of movie reviews.")

with st.spinner("Loading AI Model... (This takes a few seconds on first run)"):
    classifier = load_sentiment_model()

# 3. Load Sample Data (Optional: to show users what the data looks like)
@st.cache_data
def load_data():
    # The dataset uses a semicolon delimiter
    file_path = "netflix movie dhurandhar 2.csv"
    try:
        df = pd.read_csv(file_path, delimiter=";")
        return df
    except FileNotFoundError:
        return None

df = load_data()

# 4. Sidebar for Dataset Exploration
with st.sidebar:
    st.header("📊 Dataset Overview")
    if df is not None:
        st.write(f"Total reviews in dataset: **{len(df)}**")
        if st.checkbox("Show Sample Data"):
            st.dataframe(df.head())
    else:
        st.warning("CSV file not found. Ensure 'netflix movie dhurandhar 2.csv' is in the same directory.")

# 5. Main UI: User Input
st.subheader("📝 Test Your Own Review")
user_review = st.text_area("Write a review for Dhurandhar 2:", placeholder="e.g., The movie was absolutely fantastic with great action sequences!")

# 6. Inference and Prediction
if st.button("Analyze Sentiment"):
    if user_review.strip() == "":
        st.warning("Please enter a review first!")
    else:
        # Run the model
        result = classifier(user_review)[0]
        label = result['label']
        score = result['score']

        # Display results with dynamic styling
        st.divider()
        if label == "POSITIVE":
            st.success(f"**Sentiment:** {label} 🟢")
        else:
            st.error(f"**Sentiment:** {label} 🔴")

        st.info(f"**Confidence Score:** {score:.4f} ({score * 100:.2f}%)")
